create table if not exists public.hedge_funds (
  filer_id integer primary key,
  filer text,
  business_phone text,
  whale_score_1_yr_equal_wt integer,
  whale_score_1_yr_mgr_wt integer,
  whale_score_qtr_equal_wt integer,
  fund_size text,
  holdings numeric,
  f_13f_aum numeric,
  turnover numeric,
  pct_in_top_10 numeric,
  perf_equal_qoq numeric,
  perf_equal_all numeric,
  perf_mgr_qoq numeric,
  perf_mgr_all numeric,
  earliest_13f timestamptz,
  perf_equal_1_year numeric,
  perf_equal_5_year numeric,
  perf_mgr_wt_1_year numeric,
  perf_mgr_wt_5_year numeric,
  perf_3_yr_annualized numeric,
  perf_5_yr_annualized numeric,
  perf_7_yr_annualized numeric,
  perf_10_yr_annualized numeric,
  perf_mgr_wt_3_yr_annualized numeric,
  perf_mgr_wt_5_yr_annualized numeric,
  perf_mgr_wt_7_yr_annualized numeric,
  perf_mgr_wt_10_yr_annualized numeric,
  avg_time_in_top_10 numeric,
  avg_time_held numeric,
  filer_cik text,
  filer_zip_code text,
  change_in_mv numeric,
  put_count integer,
  call_count integer,
  prior_mv numeric,
  state text,
  city text,
  shares_traded numeric,
  sortino_3_yr_equal_weight numeric,
  stddev_3_yr numeric,
  beta_5_yr numeric,
  alpha_3_yr numeric,
  etf_aum numeric,
  etf_aum_pct numeric,
  option_aum numeric,
  option_aum_pct numeric,
  call_aum numeric,
  call_aum_pct numeric,
  put_aum numeric,
  put_aum_pct numeric,
  investing_styles text,
  fund_classifications text,
  first_date_13f_filed timestamptz,
  previous_13f_aum numeric,
  country text,
  date_filed timestamptz
);

create or replace function public.upsert_hedge_fund(data jsonb)
returns void
language plpgsql
security definer
as $$
begin
  insert into public.hedge_funds
  select * from jsonb_populate_record(null::public.hedge_funds, data)
  on conflict (filer_id) do update set
    filer = excluded.filer,
    business_phone = excluded.business_phone,
    whale_score_1_yr_equal_wt = excluded.whale_score_1_yr_equal_wt,
    whale_score_1_yr_mgr_wt = excluded.whale_score_1_yr_mgr_wt,
    whale_score_qtr_equal_wt = excluded.whale_score_qtr_equal_wt,
    fund_size = excluded.fund_size,
    holdings = excluded.holdings,
    f_13f_aum = excluded.f_13f_aum,
    turnover = excluded.turnover,
    pct_in_top_10 = excluded.pct_in_top_10,
    perf_equal_qoq = excluded.perf_equal_qoq,
    perf_equal_all = excluded.perf_equal_all,
    perf_mgr_qoq = excluded.perf_mgr_qoq,
    perf_mgr_all = excluded.perf_mgr_all,
    earliest_13f = excluded.earliest_13f,
    perf_equal_1_year = excluded.perf_equal_1_year,
    perf_equal_5_year = excluded.perf_equal_5_year,
    perf_mgr_wt_1_year = excluded.perf_mgr_wt_1_year,
    perf_mgr_wt_5_year = excluded.perf_mgr_wt_5_year,
    perf_3_yr_annualized = excluded.perf_3_yr_annualized,
    perf_5_yr_annualized = excluded.perf_5_yr_annualized,
    perf_7_yr_annualized = excluded.perf_7_yr_annualized,
    perf_10_yr_annualized = excluded.perf_10_yr_annualized,
    perf_mgr_wt_3_yr_annualized = excluded.perf_mgr_wt_3_yr_annualized,
    perf_mgr_wt_5_yr_annualized = excluded.perf_mgr_wt_5_yr_annualized,
    perf_mgr_wt_7_yr_annualized = excluded.perf_mgr_wt_7_yr_annualized,
    perf_mgr_wt_10_yr_annualized = excluded.perf_mgr_wt_10_yr_annualized,
    avg_time_in_top_10 = excluded.avg_time_in_top_10,
    avg_time_held = excluded.avg_time_held,
    filer_cik = excluded.filer_cik,
    filer_zip_code = excluded.filer_zip_code,
    change_in_mv = excluded.change_in_mv,
    put_count = excluded.put_count,
    call_count = excluded.call_count,
    prior_mv = excluded.prior_mv,
    state = excluded.state,
    city = excluded.city,
    shares_traded = excluded.shares_traded,
    sortino_3_yr_equal_weight = excluded.sortino_3_yr_equal_weight,
    stddev_3_yr = excluded.stddev_3_yr,
    beta_5_yr = excluded.beta_5_yr,
    alpha_3_yr = excluded.alpha_3_yr,
    etf_aum = excluded.etf_aum,
    etf_aum_pct = excluded.etf_aum_pct,
    option_aum = excluded.option_aum,
    option_aum_pct = excluded.option_aum_pct,
    call_aum = excluded.call_aum,
    call_aum_pct = excluded.call_aum_pct,
    put_aum = excluded.put_aum,
    put_aum_pct = excluded.put_aum_pct,
    investing_styles = excluded.investing_styles,
    fund_classifications = excluded.fund_classifications,
    first_date_13f_filed = excluded.first_date_13f_filed,
    previous_13f_aum = excluded.previous_13f_aum,
    country = excluded.country,
    date_filed = excluded.date_filed
  where hedge_funds.date_filed is null or hedge_funds.date_filed < excluded.date_filed;
end;
$$;
