-- Alpha Galangal Committee LLM formula: factors, formula, prompt version, link active prompt

with cat as (
  select id as category_id
  from public.signal_categories
  where name = 'INTELLIGENCE_SYNTHESIS'
  limit 1
),

ins_factors as (
  insert into public.factors
    (id, key, name, value_type, description, data_grain, period_supported, statement_type, created_at)
  values
    (gen_random_uuid(), 'alpha_galangal_committee_buffett_score',       'Alpha Galangal Committee: Buffett Score',       'number', 'Subscore (0-100) generated by the committee LLM for Buffett',       'snapshot', 'none', 'custom', now()),
    (gen_random_uuid(), 'alpha_galangal_committee_wood_score',          'Alpha Galangal Committee: Wood Score',          'number', 'Subscore (0-100) generated by the committee LLM for Cathie Wood',    'snapshot', 'none', 'custom', now()),
    (gen_random_uuid(), 'alpha_galangal_committee_lynch_score',         'Alpha Galangal Committee: Lynch Score',         'number', 'Subscore (0-100) generated by the committee LLM for Peter Lynch',    'snapshot', 'none', 'custom', now()),
    (gen_random_uuid(), 'alpha_galangal_committee_burry_score',         'Alpha Galangal Committee: Burry Score',         'number', 'Subscore (0-100) generated by the committee LLM for Michael Burry',  'snapshot', 'none', 'custom', now()),
    (gen_random_uuid(), 'alpha_galangal_committee_druckenmiller_score', 'Alpha Galangal Committee: Druckenmiller Score', 'number', 'Subscore (0-100) generated by the committee LLM for Druckenmiller',  'snapshot', 'none', 'custom', now()),
    (gen_random_uuid(), 'alpha_galangal_committee_graham_score',        'Alpha Galangal Committee: Graham Score',        'number', 'Subscore (0-100) generated by the committee LLM for Ben Graham',     'snapshot', 'none', 'custom', now()),
    (gen_random_uuid(), 'alpha_galangal_committee_weighted_score',      'Alpha Galangal Committee: Weighted Score',      'number', 'Weighted committee score (0-100) computed from member subscores', 'snapshot', 'none', 'custom', now()),
    (gen_random_uuid(), 'alpha_galangal_committee_confidence',          'Alpha Galangal Committee: Confidence',          'number', 'Confidence (0-100) reported by the committee LLM',                   'snapshot', 'none', 'custom', now())
  on conflict (key) do nothing
  returning id
),

ins_formula as (
  insert into public.formulas
    (id, key, name, category_id, formula_level, execution_type, version, is_active, definition)
  select
    gen_random_uuid(),
    'alpha_galangal_committee_llm',
    'alpha_galangal_committee_llm',
    cat.category_id,
    'MASTER_MODEL',
    'llm',
    1,
    true,
    '{"type":"llm"}'::jsonb
  from cat
  returning id as formula_id
),

ins_prompt as (
  insert into public.formula_prompt_versions
    (id, formula_id, version, status, system_prompt, user_prompt_template, output_schema, model_name, temperature, max_output_tokens, created_at)
  select
    gen_random_uuid(),
    ins_formula.formula_id,
    1,
    'active',

    $SYS$
You are "Alpha Galangal Committee", an internal investment committee of six notable investors:
- Warren Buffett (20%) — Moat & intrinsic value
- Michael Burry (15%) — Contrarian deep value / dislocation
- Stanley Druckenmiller (20%) — Macro + momentum
- Cathie Wood (10%) — Disruptive innovation / TAM
- Benjamin Graham (15%) — Quant value + balance sheet safety
- Peter Lynch (20%) — Practical growth (GARP)

Rules:
1) Use the provided factor bundle as ground truth. Do not invent numbers.
2) Produce a 0–100 score for each member.
3) Compute a weighted_score (0–100) using the weights above.
4) Provide confidence 0–100.
5) Provide a summary max 3 sentences.
6) Return valid JSON only. No markdown.
$SYS$,

    $USR$
Evaluate {{ticker}} using the committee framework.

Factor bundle (latest snapshot + derived metrics + optional time-series summaries):
{{factor_bundle_json}}

Return JSON with exactly this structure:
{
  "ticker": "",
  "member_scores": {
    "buffett": 0,
    "burry": 0,
    "druckenmiller": 0,
    "wood": 0,
    "graham": 0,
    "lynch": 0
  },
  "weighted_score": 0,
  "confidence": 0,
  "summary": "",
  "key_strengths": [],
  "key_risks": []
}

Constraints:
- summary must be <= 3 sentences
- do not fabricate missing financial values; if missing, reflect uncertainty in confidence
$USR$,

    '{
      "required_keys": ["ticker","member_scores","weighted_score","confidence","summary","key_strengths","key_risks"],
      "member_keys": ["buffett","burry","druckenmiller","wood","graham","lynch"]
    }'::jsonb,

    'gemini-2.5-flash',
    0.2,
    800,
    now()
  from ins_formula
  returning id as prompt_version_id, formula_id
)

update public.formulas f
set active_prompt_version_id = ins_prompt.prompt_version_id
from ins_prompt
where f.id = ins_prompt.formula_id;
