BEGIN;

INSERT INTO public.social_platform_post_specs (
  platform,
  post_kind,
  is_enabled,
  api_support_level,
  enforcement_mode,
  csv_source_label,
  facet_capabilities,
  notes
) VALUES
  ('facebook', 'text', true, 'yes', 'block',
   'Facebook Text post', '{}'::jsonb, 'MVP YES'),
  ('facebook', 'single_image', true, 'yes', 'block',
   'Facebook Single image post', '{}'::jsonb, 'MVP YES'),
  ('facebook', 'multi_image', true, 'yes', 'block',
   'Facebook Multi-image/carousel post', '{}'::jsonb, 'MVP YES'),
  ('facebook', 'video', true, 'yes', 'block',
   'Facebook Video post', '{}'::jsonb, 'MVP YES'),
  ('facebook', 'reel', true, 'yes', 'block',
   'Facebook Reel', '{}'::jsonb, 'MVP YES'),
  ('facebook', 'story', false, 'partial', 'warn',
   'Facebook Story', '{}'::jsonb, 'MVP UNSURE'),
  ('facebook', 'link_share', true, 'yes', 'block',
   'Facebook Link/share post', '{}'::jsonb, 'MVP YES'),

  ('instagram', 'single_image', true, 'yes', 'block',
   'Instagram Single image post', '{}'::jsonb, 'MVP YES'),
  ('instagram', 'multi_image', true, 'yes', 'block',
   'Instagram Carousel/multi-image post', '{}'::jsonb, 'MVP YES'),
  ('instagram', 'video', true, 'yes', 'block',
   'Instagram Video feed post', '{}'::jsonb, 'MVP YES'),
  ('instagram', 'reel', true, 'yes', 'block',
   'Instagram Reel', '{}'::jsonb, 'MVP YES'),
  ('instagram', 'story', true, 'yes', 'block',
   'Instagram Story', '{}'::jsonb, 'MVP YES'),

  ('tiktok', 'video', true, 'yes', 'block',
   'TikTok Video post', '{}'::jsonb, 'MVP YES'),
  ('tiktok', 'multi_image', true, 'yes', 'block',
   'TikTok Photo/slideshow + Carousel/slideshow', '{}'::jsonb, 'MVP YES'),
  ('tiktok', 'story', false, 'partial', 'warn',
   'TikTok Story', '{}'::jsonb, 'MVP UNSURE'),
  ('tiktok', 'live_stream', false, 'partial', 'warn',
   'TikTok Live stream', '{}'::jsonb, 'MVP UNSURE'),

  ('stocktwits', 'text', true, 'yes', 'block',
   'StockTwits Text message (+ cashtag via post_facets)',
   '{"supports_sentiment": true, "supports_cashtag": true, "allows_text_with_other_media": true}'::jsonb,
   'Combine GIF/image+caption+cashtag+sentiment via post_facets and assets.'),
  ('stocktwits', 'single_image', true, 'yes', 'block',
   'StockTwits Single image post',
   '{"supports_sentiment": true, "supports_cashtag": true}'::jsonb, 'MVP YES'),
  ('stocktwits', 'gif', true, 'yes', 'block',
   'StockTwits GIF/media post',
   '{"supports_sentiment": true, "supports_cashtag": true}'::jsonb, 'MVP YES'),
  ('stocktwits', 'link_share', true, 'yes', 'warn',
   'StockTwits Link/share post',
   '{"supports_sentiment": true, "supports_cashtag": true}'::jsonb,
   'CSV notes: visibility may suffer with links'),
  ('stocktwits', 'thread_reply', true, 'yes', 'block',
   'StockTwits Reply/thread post',
   '{"supports_sentiment": true, "supports_cashtag": true, "requires_reply_parent": true}'::jsonb,
   'Requires post_facets.reply_to'),

  ('x', 'text', true, 'yes', 'block',
   'X Text post', '{}'::jsonb, 'MVP YES'),
  ('x', 'single_image', true, 'yes', 'block',
   'X Single image post', '{}'::jsonb, 'MVP YES'),
  ('x', 'multi_image', true, 'yes', 'block',
   'X Multi-image post', '{}'::jsonb, 'MVP YES'),
  ('x', 'video', true, 'yes', 'block',
   'X Video post', '{}'::jsonb, 'MVP YES'),
  ('x', 'gif', true, 'yes', 'block',
   'X GIF post', '{}'::jsonb, 'MVP YES'),
  ('x', 'link_share', true, 'yes', 'block',
   'X Link preview post', '{}'::jsonb, 'MVP YES'),
  ('x', 'poll', false, 'yes', 'block',
   'X Poll', '{}'::jsonb, 'CSV FUTURE'),

  ('linkedin', 'text', true, 'yes', 'block',
   'LinkedIn Text post', '{}'::jsonb, 'MVP YES'),
  ('linkedin', 'single_image', true, 'yes', 'block',
   'LinkedIn Single image post', '{}'::jsonb, 'MVP YES'),
  ('linkedin', 'multi_image', true, 'yes', 'block',
   'LinkedIn Multi-image/carousel document (+ swipe)',
   '{"supports_linkedin_document_presentation": true}'::jsonb,
   'post_facets.presentation = linkedin_document when using document API'),
  ('linkedin', 'video', true, 'yes', 'block',
   'LinkedIn Video post', '{}'::jsonb, 'MVP YES'),
  ('linkedin', 'link_share', true, 'yes', 'block',
   'LinkedIn Link/share post', '{}'::jsonb, 'MVP YES'),

  ('stocktwits', 'poll', false, 'partial', 'warn',
   'StockTwits Poll', '{}'::jsonb, 'MVP UNSURE');

COMMIT;
